apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-pod-scaling-learning-record-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: learning-record-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 60
        type: Utilization
