CREATE TABLE IF NOT EXISTS sectionEnrollmentRecord(
enrollment_id STRING  NOT NULL OPTIONS(description = "enrollment uuid generated by firestore"),
email STRING  NOT NULL OPTIONS(description = "User email"),
`role` STRING  NOT NULL OPTIONS(description = "User enrollment role"),
`status` STRING  NOT NULL OPTIONS(description = "enrollment status"),
invitation_id STRING OPTIONS(description = "invitation id generated by classroom"),
section_id STRING  NOT NULL OPTIONS(description = "section unique id"),
cohort_id STRING  NOT NULL OPTIONS(description = "cohort unique id"),
course_id STRING  NOT NULL OPTIONS(description = "classroom id"),
`timestamp` TIMESTAMP)