CREATE TABLE IF NOT EXISTS submittedCourseWorkCollection (
        uuid STRING NOT NULL OPTIONS(description = "unique id"),
        courseId STRING NOT NULL OPTIONS(description = "course id"),
        courseWorkId STRING NOT NULL OPTIONS(description = "course work id"),
        id STRING NOT NULL OPTIONS(description = "submitted course work id"),
        userId STRING NOT NULL OPTIONS(description = "user id (guy id)"),
        creationTime TIMESTAMP,
        updateTime TIMESTAMP,
        `state` STRING OPTIONS(description = "submitted course work state"),
        late BOOL,
        draftGrade NUMERIC,
        assignedGrade NUMERIC,
        alternateLink STRING OPTIONS(description = "submitted course work link"),
        courseWorkType STRING OPTIONS(description = "course work type"),
        associatedWithDeveloper BOOL,
        assignmentSubmission JSON,
        submissionHistory ARRAY<JSON>,
        shortAnswerSubmission JSON,
        multipleChoiceSubmission JSON,
        event_type STRING,
        `timestamp` TIMESTAMP,
        message_id STRING NOT NULL);