apiVersion: apps/v1
kind: Deployment
metadata:
  name: credential-pathway-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: credential-pathway-service
        image: gcr.io/core-learning-services-dev/credential-pathway-service
        imagePullPolicy: Always
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: PROJECT_ID
        - name: DATABASE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: DATABASE_PREFIX
