apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: deep-knowledge-tracing
requires:
  - path: ../../common
    configs: [common]
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: deep-knowledge-tracing
    requires:
      - image: common
        alias: BASE_IMG
    sync:
      infer:
        - "**/*.py"
        - "**/*.json"
portForward:
- resourceType: service
  resourceName: deep-knowledge-tracing
  port: 80
  localPort: 9010
deploy:
  kustomize:
    paths:
    - ./kustomize/minikube
  statusCheckDeadlineSeconds: 1200
profiles:
- name: custom
  build:
    googleCloudBuild:
      machineType: N1_HIGHCPU_8
      timeout: '1500s'
    artifacts:
    - image: deep-knowledge-tracing
      docker:
          cacheFrom:
            - deep-knowledge-tracing
            - deep-knowledge-tracing:latest
      requires:
        - image: common
          alias: BASE_IMG
  deploy:
    kustomize:
      paths:
      - ./kustomize/custom
    statusCheckDeadlineSeconds: 1200
- name: dev
  activation:
  - kubeContext: gke_gcp-classroom-dev_us-central1_gcp-classroom-dev-us-central1
  build:
    googleCloudBuild:
      machineType: N1_HIGHCPU_8
      timeout: '1500s'
    artifacts:
    - image: gcr.io/gcp-classroom-dev/deep-knowledge-tracing
      docker:
          cacheFrom:
            - gcr.io/gcp-classroom-dev/deep-knowledge-tracing:latest
      requires:
        - image: gcr.io/gcp-classroom-dev/common
          alias: BASE_IMG
      sync:
        infer:
          - "**/*.py"
          - "**/*.json"
          - "**/*.yaml"
  deploy:
    kustomize:
      paths:
      - ./kustomize/dev
    statusCheckDeadlineSeconds: 1200

- name: gpu
  build:
    googleCloudBuild:
      machineType: N1_HIGHCPU_8
      timeout: '3000s'
    artifacts:
    - image: gcr.io/gcp-classroom-dev/deep-knowledge-tracing
      docker:
          cacheFrom:
            - deep-knowledge-tracing
            - deep-knowledge-tracing:latest
            - gcr.io/gcp-classroom-dev/deep-knowledge-tracing:latest
      requires:
        - image: gcr.io/gcp-classroom-dev/common
          alias: BASE_IMG
      sync:
        infer:
          - "**/*.py"
          - "**/*.json"
          - "**/*.yaml"
  deploy:
    kustomize:
      paths:
      - ./kustomize/gpu
    statusCheckDeadlineSeconds: 1200

- name: prod
  build:
    googleCloudBuild:
      machineType: N1_HIGHCPU_8
      timeout: '1500s'
    artifacts:
    - image: deep-knowledge-tracing
      docker:
          cacheFrom:
            - deep-knowledge-tracing
            - deep-knowledge-tracing:latest
      requires:
        - image: common
          alias: BASE_IMG
  deploy:
    kustomize:
      paths:
      - ./kustomize/prod
    statusCheckDeadlineSeconds: 1200