apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-object-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: learning-object-service
        image: gcr.io/aitutor-dev/learning-object-service
        imagePullPolicy: Always
        env:
        - name: GCP_PROJECT
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: GCP_PROJECT
        - name: DATABASE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: DATABASE_PREFIX
        - name: CONTENT_SERVING_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: CONTENT_SERVING_BUCKET 
