apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-object-service
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: learning-object-service
        image: learning-object-service
        imagePullPolicy: Always
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: PROJECT_ID
        - name: EXTERNAL_DATA_GCP_PROJECT
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: EXTERNAL_DATA_GCP_PROJECT
        - name: CONTENT_SERVING_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: CONTENT_SERVING_BUCKET
        - name: DATABASE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: DATABASE_PREFIX