apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-pod-scaling-skill-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skill-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    #resource:
    #  name: memory
    #  targetAverageValue: 500Mi
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
