# Master Skaffold
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: backends
requires:
- path: ./common
  configs: [common]

- path: ./microservices/sample_service
  configs: [sample-service]

profiles:
- name: custom
- name: prod
- name: dev
  activation:
    - kubeContext: gke_core-learning-services-dev_us-central1_core-learning-services-dev-us-central1