apiVersion: apps/v1
kind: Deployment
metadata:
  name: lti-service
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: lti-service
        image: lti-service
        imagePullPolicy: Always
        env:
        - name: GCP_PROJECT
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: GCP_PROJECT
