apiVersion: v1
kind: Service
metadata:
  name: matching-engine
  labels:
    app: matching-engine
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: matching-engine
