apiVersion: v1
kind: Service
metadata:
  name: api-docs
  labels:
    app: api-docs
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # Creates a NEG after an Ingress is created
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9029
  selector:
    app: api-docs