apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-pod-scaling-matching-engine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: matching-engine
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    #resource:
    #  name: memory
    #  targetAverageValue: 500Mi
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
