apiVersion: apps/v1
kind: Deployment
metadata:
  name: utils
spec:
  template:
    spec:
      containers:
      - name: utils
        image: utils
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "500Mi"
