CREATE OR REPLACE VIEW
`lms_analytics.courseWorkCollEnrichedView` as
with coursework as
(SELECT uuid,			
id as courseWork_id,			
courseId as courseWork_courseId,			
title as courseWork_title,			
description as courseWork_description,			
materials as courseWork_materials,			
`state` as courseWork_state,			
alternateLink as courseWork_alternateLink,			
creationTime as courseWork_creationTime,			
updateTime as courseWork_updateTime,			
dueDate as courseWork_dueDate,			
dueTime as courseWork_dueTime,			
scheduledTime as courseWork_scheduledTime,			
maxPoints as courseWork_maxPoints,			
workType as courseWork_workType,			
associatedWithDeveloper as courseWork_associatedWithDeveloper,			
assigneeMode as courseWork_assigneeMode,			
individualStudentsOptions as courseWork_individualStudentsOptions,			
submissionModificationMode as courseWork_submissionModificationMode,			
creatorUserId as courseWork_creatorUserId,			
topicId as courseWork_topicId,			
gradeCategory as courseWork_gradeCategory,			
`assignment` as courseWork_assignment,			
multipleChoiceQuestion as courseWork_multipleChoiceQuestion,			
event_type as courseWork_event_type,			
`timestamp` as courseWork_timestamp,			
message_id as courseWork_message_id FROM
`lms_analytics.courseWorkCollectionView`), course as (
  SELECT 
      section.courseId as course_id,
      section.courseTemplateName as course_name,
      section.sectionName as course_section,
      section.description as course_description,
      section.classroomUrl as course_url,
      section.sectionId as section_id,
      section.courseTemplateName as section_name,
      section.maxStudents as section_max_students,
      section.status as section_status,
      section.enrollmentStatus as section_enrollment_status,
      cohort.cohortId as cohort_id,
      cohort.name as cohort_name,
      cohort.description as cohort_description,
      cohort.registrationStartDate as cohort_registration_start_date,
      cohort.registrationEndDate as cohort_registration_end_date,
      cohort.startDate as cohort_start_date,
      cohort.endDate as cohort_end_date,
      cohort.maxStudents as cohort_max_students  
      FROM `lms_analytics.sectionView` as section JOIN
      `lms_analytics.cohortView` as cohort 
      on section.cohortId=cohort.cohortId )
      
SELECT 
        uuid,
        courseWork_id,
        courseWork_title,
        course_id,
        course_name,
        course_section,
        courseWork_description,			
        courseWork_materials,			
        courseWork_state,			
        courseWork_alternateLink,			
        courseWork_creationTime,			
        courseWork_updateTime,			
        courseWork_dueDate,			
        courseWork_dueTime,			
        courseWork_scheduledTime,			
        courseWork_maxPoints,			
        courseWork_workType,			
        courseWork_associatedWithDeveloper,			
        courseWork_assigneeMode,			
        courseWork_individualStudentsOptions,			
        courseWork_submissionModificationMode,			
        courseWork_creatorUserId,			
        courseWork_topicId,			
        courseWork_gradeCategory,			
        courseWork_assignment,			
        courseWork_multipleChoiceQuestion,			
        courseWork_event_type,			
        courseWork_timestamp,			
        courseWork_message_id,
        section_id,
        course.section_name,
        course.cohort_id,
        course.cohort_name,
        course.cohort_description,
        course.cohort_registration_start_date,
        course.cohort_registration_end_date,
        course.cohort_start_date,
        course.cohort_end_date,
        course.cohort_max_students
 FROM coursework 
 JOIN course ON course.course_id=coursework.courseWork_courseId 
 ORDER BY course.course_id