CREATE TABLE IF NOT EXISTS courseWorkCollection (
        uuid STRING NOT NULL OPTIONS(description = "unique id"),
        id STRING NOT NULL OPTIONS(description = "course work id"),
        courseId STRING NOT NULL OPTIONS(description = "course id"),
        title STRING OPTIONS(description = "course work name"),
        `description` STRING OPTIONS(description = "course work description"),
        materials ARRAY <JSON>,
        `state` STRING OPTIONS(description = "course work state"),
        alternateLink STRING OPTIONS(description = "course work link"),
        creationTime TIMESTAMP,
        updateTime TIMESTAMP,
        dueDate STRUCT<`year` INTEGER, `month` INTEGER, `day` INTEGER>,
        dueTime STRUCT<`hours` INTEGER,`minutes` INTEGER,`seconds` INTEGER,`nanos` INTEGER>,
        scheduledTime STRING,
        maxPoints INTEGER,
        workType STRING,
        associatedWithDeveloper BOOL,
        `assigneeMode` STRING,
        individualStudentsOptions JSON,
        submissionModificationMode STRING,
        creatorUserId STRING,
        topicId STRING,
        gradeCategory JSON,
        assignment JSON,
        multipleChoiceQuestion JSON,
        `timestamp` TIMESTAMP,
        message_id STRING NOT NULL);