apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: llm-service
        image: gcr.io/aitutor-dev/llm-service
        imagePullPolicy: Always
        env:
        - name: GCP_PROJECT
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: GCP_PROJECT
        - name: DATABASE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: DATABASE_PREFIX
        - name: ONET_USERNAME
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: ONET_USERNAME
        - name: ONET_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: ONET_PASSWORD
        - name: USE_STATIC_LEARNOSITY_DATA
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: USE_STATIC_LEARNOSITY_DATA
