apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assessment-service
  template:
    metadata:
      labels:
        app: assessment-service
    spec:
      serviceAccountName: ksa
      # TODO: un-comment the below steps while updating workflows
      # volumes:	
      #   - name: signurl-sa-key	
      #     secret:	
      #       secretName: signurl-sa-key
      containers:
      - name: assessment-service
        image: assessment-service
        # volumeMounts:	
        #   - mountPath: /opt/keys	
        #     name: signurl-sa-key	
        #     readOnly: true
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "500m"
            memory: "1000Mi"
          limits:
            memory: "5000Mi"
            cpu: "2000m"
        env:
        # Define the environment variable
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: PROJECT_ID
        - name: API_BASE_URL
          # Required format: api/version
          value: api/v1
        - name: CONTAINER_NAME
          value: assessment-service
        - name: DEPLOYMENT_NAME
          value: assessment-service
        - name: SERVICE_NAME
          value: assessment-service
        - name: IS_DEVELOPMENT
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: IS_DEVELOPMENT 
        ports:
        - containerPort: 80
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /ping
            port: 80
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 60
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /ping
            port: 80
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 60
