apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-response-theory
spec:
  template:
    spec:
      containers:
      - name: item-response-theory
        image: gcr.io/core-learning-services-dev/item-response-theory
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1000Mi"
        env:
        - name: DATABASE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: DATABASE_PREFIX

