# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: citizen-360-app
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: citizen-360-app
        image: citizen-360-app
        imagePullPolicy: Always
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: PROJECT_ID
        - name: EXTERNAL_DATA_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: EXTERNAL_DATA_PROJECT_ID
