apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-pod-scaling-extractive-summarization
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: extractive-summarization
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
