apiVersion: apps/v1
kind: Deployment
metadata:
  name: lti-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: lti-service
        image: gcr.io/aitutor-dev/lti-service
        imagePullPolicy: Always
        env:
        - name: GCP_PROJECT
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: GCP_PROJECT
        - name: DATABASE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: DATABASE_PREFIX