/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

let clpServices = require("./clp_services.json")
let redocusaurusSpecs = []

for (let service of clpServices) {
  let data = { type: "link", href: service.route, label: service.label }
  redocusaurusSpecs.push(data)
}


/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebar: [
    { type: "autogenerated", dirName: "." },
    {
      type: "category",
      label: "API Reference Docs",
      // @ts-ignore
      items: [...redocusaurusSpecs]
    }
  ]
};

module.exports = sidebars;
