apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-learner-profile
spec:
  template:
    spec:
      containers:
      - name: student-learner-profile
        image: student-learner-profile
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "500Mi"
        env:
        - name: DATABASE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: DATABASE_PREFIX
