apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: course-ingestion
requires:
  - path: ../../common
    configs: [common]
  - path: ../extractive_summarization
    configs: [extractive-summarization]
build:
  tagPolicy:
    gitCommit:
      ignoreChanges: true
  artifacts:
  - image: course-ingestion
    requires:
      - image: common
        alias: BASE_IMG
    sync:
      infer:
        - "**/*.py"
        - "**/*.json"
portForward:
- resourceType: service
  resourceName: course-ingestion
  port: 80
  localPort: 9006
deploy:
  kustomize:
    paths:
    - ./kustomize/minikube
  statusCheckDeadlineSeconds: 1200
profiles:
- name: custom
  build:
    googleCloudBuild:
      machineType: N1_HIGHCPU_8
      timeout: '3000s'
    artifacts:
    - image: course-ingestion
      docker:
          cacheFrom:
            - course-ingestion
            - course-ingestion:latest
      requires:
        - image: common
          alias: BASE_IMG
  deploy:
    kustomize:
      paths:
      - ./kustomize/custom
    statusCheckDeadlineSeconds: 1200
- name: dev
  activation:
  - kubeContext: gke_gcp-classroom-dev_us-central1_gcp-classroom-dev-us-central1
  build:
    googleCloudBuild:
      machineType: N1_HIGHCPU_8
      timeout: '3000s'
    artifacts:
    - image: gcr.io/gcp-classroom-dev/course-ingestion
      docker:
          cacheFrom:
            - gcr.io/gcp-classroom-dev/course-ingestion:latest
      requires:
        - image: gcr.io/gcp-classroom-dev/common
          alias: BASE_IMG
      sync:
        infer:
          - "**/*.py"
          - "**/*.json"
          - "**/*.yaml"
  deploy:
    kustomize:
      paths:
      - ./kustomize/dev
    statusCheckDeadlineSeconds: 1200

- name: gpu
  build:
    googleCloudBuild:
      machineType: N1_HIGHCPU_8
      timeout: '3000s'
    artifacts:
    - image: gcr.io/gcp-classroom-dev/course-ingestion
      docker:
          cacheFrom:
            - course-ingestion
            - course-ingestion:latest
            - gcr.io/gcp-classroom-dev/course-ingestion:latest
      requires:
        - image: gcr.io/gcp-classroom-dev/common
          alias: BASE_IMG
      sync:
        infer:
          - "**/*.py"
          - "**/*.json"
          - "**/*.yaml"
  deploy:
    kustomize:
      paths:
      - ./kustomize/gpu
    statusCheckDeadlineSeconds: 1200

- name: prod
  build:
    googleCloudBuild:
      machineType: N1_HIGHCPU_8
      timeout: '3000s'
    artifacts:
    - image: course-ingestion
      docker:
          cacheFrom:
            - course-ingestion
            - course-ingestion:latest
      requires:
        - image: common
          alias: BASE_IMG
  deploy:
    kustomize:
      paths:
      - ./kustomize/prod
    statusCheckDeadlineSeconds: 1200