apiVersion: apps/v1
kind: Deployment
metadata:
  name: prior-learning-assessment
spec:
  template:
    spec:
      containers:
      - name: prior-learning-assessment
        image: prior-learning-assessment
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "500Mi"
