apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: learning-record-service
requires:
  - path: ../../common
    configs: [common]
    activeProfiles:
    - name: custom
      activatedBy: [custom]
    - name: dev
      activatedBy: [dev]
    - name: prod
      activatedBy: [prod]
build:
  tagPolicy:
    gitCommit: {}
  local:
    concurrency: 0
  artifacts:
  - image: learning-record-service
    requires:
      - image: common
        alias: BASE_IMG
    sync:
      infer:
        - '**/*.py'
        - '**/*.json'
portForward:
- resourceType: service
  resourceName: learning-record-service
  port: 80
  localPort: 8888
manifests:
  kustomize:
    paths:
    - ./kustomize/minikube
profiles:
- name: custom
  build:
    googleCloudBuild: {}
    artifacts:
    - image: learning-record-service
      docker:
        cacheFrom:
          - learning-record-service:latest
      requires:
        - image: common
          alias: BASE_IMG
  manifests:
    kustomize:
      paths:
      - ./kustomize/custom
  deploy:
    kubectl: {}

- name: prod_non_cloudbuild
  manifests:
    kustomize:
      paths:
      - ./kustomize/prod
  deploy:
    kubectl: {}

- name: dev
  activation:
  - kubeContext: gke_core-learning-services-dev_us-central1_core-learning-services-dev-us-central1
  build:
    googleCloudBuild: {}
    artifacts:
    - image: gcr.io/core-learning-services-dev/learning-record-service
      docker:
        cacheFrom:
          - gcr.io/core-learning-services-dev/learning-record-service
          - gcr.io/core-learning-services-dev/learning-record-service:latest
      requires:
        - image: gcr.io/core-learning-services-dev/common
          alias: BASE_IMG
      sync:
        infer:
          - '**/*.py'
          - '**/*.json'
  manifests:
    kustomize:
      paths:
      - ./kustomize/dev
  deploy:
    kubectl: {}

- name: prod
  build:
    googleCloudBuild: {}
    artifacts:
    - image: learning-record-service
      docker:
        cacheFrom:
          - learning-record-service
          - learning-record-service:latest
      requires:
        - image: common
          alias: BASE_IMG
  manifests:
    kustomize:
      paths:
      - ./kustomize/prod
  deploy:
    kubectl: {}
