apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-ingestion
spec:
  template:
    spec:
      containers:
      - name: course-ingestion
        image: course-ingestion
        imagePullPolicy: IfNotPresent
        env:
        - name: GCP_LEARNING_RESOURCE_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: GCP_LEARNING_RESOURCE_BUCKET
