apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: assessment-service
requires:
  - path: ../../common
    configs: [common]
build:
  tagPolicy:
    gitCommit:
      ignoreChanges: true
  local:
    concurrency: 0
  artifacts:
  - image: assessment-service
    requires:
      - image: common
        alias: BASE_IMG
    sync:
      infer:
        - '**/*.py'
        - '**/*.json'
portForward:
- resourceType: service
  resourceName: assessment-service
  port: 80
  localPort: 8888
deploy:
  kustomize:
    paths:
    - ./kustomize/minikube
profiles:
- name: custom
  build:
    googleCloudBuild: {}
    artifacts:
    - image: assessment-service
      docker:
        cacheFrom:
          - assessment-service:latest
      requires:
        - image: common
          alias: BASE_IMG
  deploy:
    kustomize:
      paths:
      - ./kustomize/custom
- name: prod_non_cloudbuild
  deploy:
    kustomize:
      paths:
      - ./kustomize/prod
- name: dev
  activation:
  - kubeContext: gke_gcp-classroom-dev_us-central1_gcp-classroom-dev-us-central1
  build:
    googleCloudBuild: {}
    artifacts:
    - image: gcr.io/gcp-classroom-dev/assessment-service
      docker:
        cacheFrom:
          - gcr.io/gcp-classroom-dev/assessment-service
          - gcr.io/gcp-classroom-dev/assessment-service:latest
      requires:
        - image: gcr.io/gcp-classroom-dev/common
          alias: BASE_IMG
      sync:
        infer:
          - '**/*.py'
          - '**/*.json'
  deploy:
    kustomize:
      paths:
      - ./kustomize/dev
- name: prod
  build:
    googleCloudBuild: {}
    artifacts:
    - image: assessment-service
      docker:
        cacheFrom:
          - assessment-service
          - assessment-service:latest
      requires:
        - image: common
          alias: BASE_IMG
  deploy:
    kustomize:
      paths:
      - ./kustomize/prod