apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: item-response-theory
requires:
  - path: ../../common_ml
    configs: [common-ml]
    activeProfiles:
    - name: custom
      activatedBy: [custom]
    - name: dev
      activatedBy: [dev]
    - name: prod
      activatedBy: [prod]
    - name: gpu
      activatedBy: [gpu]
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: item-response-theory
    requires:
      - image: common-ml
        alias: ML_BASE_IMG
    sync:
      infer:
        - "**/*.py"
        - "**/*.json"
portForward:
- resourceType: service
  resourceName: item-response-theory
  port: 80
  localPort: 8915
deploy:
  kustomize:
    paths:
    - ./kustomize/minikube
  statusCheckDeadlineSeconds: 1200
profiles:
- name: custom
  build:
    googleCloudBuild:
      machineType: N1_HIGHCPU_8
      timeout: '1500s'
    artifacts:
    - image: item-response-theory
      docker:
          cacheFrom:
            - item-response-theory
            - item-response-theory:latest
      requires:
        - image: common-ml
          alias: ML_BASE_IMG
  deploy:
    kustomize:
      paths:
      - ./kustomize/custom
    statusCheckDeadlineSeconds: 1200

- name: dev
  build:
    googleCloudBuild:
      machineType: N1_HIGHCPU_8
      timeout: '1500s'
    artifacts:
    - image: gcr.io/aitutor-dev/item-response-theory
      docker:
          cacheFrom:
            - gcr.io/aitutor-dev/item-response-theory:latest
      requires:
        - image: gcr.io/aitutor-dev/common-ml
          alias: ML_BASE_IMG
      sync:
        infer:
          - "**/*.py"
          - "**/*.json"
          - "**/*.yaml"
  deploy:
    kustomize:
      paths:
      - ./kustomize/dev
    statusCheckDeadlineSeconds: 1200

- name: gpu
  build:
    googleCloudBuild:
      machineType: N1_HIGHCPU_8
      timeout: '1500s'
    artifacts:
    - image: gcr.io/aitutor-dev/item-response-theory
      docker:
          cacheFrom:
            - item-response-theory
            - item-response-theory:latest
            - gcr.io/aitutor-dev/item-response-theory:latest
      requires:
        - image: gcr.io/aitutor-dev/common-ml
          alias: ML_BASE_IMG
      sync:
        infer:
          - "**/*.py"
          - "**/*.json"
          - "**/*.yaml"
  deploy:
    kustomize:
      paths:
      - ./kustomize/gpu
    statusCheckDeadlineSeconds: 1200

- name: prod
  build:
    googleCloudBuild:
      machineType: N1_HIGHCPU_8
      timeout: '1500s'
    artifacts:
    - image: item-response-theory
      docker:
          cacheFrom:
            - item-response-theory
            - item-response-theory:latest
      requires:
        - image: common-ml
          alias: ML_BASE_IMG
  deploy:
    kustomize:
      paths:
      - ./kustomize/prod
    statusCheckDeadlineSeconds: 1200