apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-learner-profile
spec:
  replicas: 3
  template:
    spec:
      serviceAccountName: ksa
      containers:
      - name: student-learner-profile
        image: student-learner-profile
        imagePullPolicy: Always
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: PROJECT_ID
        - name: EXTERNAL_DATA_GCP_PROJECT
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: EXTERNAL_DATA_GCP_PROJECT