apiVersion: v1
kind: Service
metadata:
  name: credential-pathway-service
  labels:
    app: credential-pathway-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: credential-pathway-service
