apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: ksa
      containers:
      - name: lms
        image: gcr.io/core-learning-services-dev/lms
        imagePullPolicy: Always