apiVersion: v1
kind: Service
metadata:
  name: item-response-theory
  labels:
    app: item-response-theory
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: item-response-theory