apiVersion: v1
kind: Service
metadata:
  name: prior-learning-assessment
  labels:
    app: prior-learning-assessment
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: prior-learning-assessment