apiVersion: v1
kind: Service
metadata:
  name: skill-service
  labels:
    app: skill-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: skill-service
