apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractive-summarization
spec:
  template:
    spec:
      containers:
      - name: extractive-summarization
        image: gcr.io/aitutor-dev/extractive-summarization
        imagePullPolicy: Always
        resources:
          requests:
            memory: "700Mi"
            cpu: "1000m"
          limits:
            memory: "3000Mi"
            cpu: "8000m"
