apiVersion: apps/v1
kind: Deployment
metadata:
  name: prior-learning-assessment
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: ksa
      containers:
      - name: prior-learning-assessment
        image: gcr.io/core-learning-services-dev/prior-learning-assessment
        imagePullPolicy: Always
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: PROJECT_ID
        - name: DATABASE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: DATABASE_PREFIX
