apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: lms
requires:
  - path: ../../common
    configs: [common]
build:
  tagPolicy:
    gitCommit: {}
  local:
    concurrency: 0
  artifacts:
  - image: lms
    requires:
      - image: common
        alias: BASE_IMG
    sync:
      infer:
        - '**/*.py'
        - '**/*.json'
portForward:
- resourceType: service
  resourceName: lms
  port: 80
  localPort: 8888
deploy:
  kustomize:
    paths:
    - ./kustomize/minikube
profiles:
- name: custom
  build:
    googleCloudBuild: {}
    artifacts:
    - image: lms
      requires:
      - image: common
        alias: BASE_IMG
  deploy:
    kustomize:
      paths:
      - ./kustomize/custom
- name: prod_non_cloudbuild
  deploy:
    kustomize:
      paths:
      - ./kustomize/prod
- name: prod
  deploy:
    kustomize:
      paths:
      - ./kustomize/prod
  build:
    googleCloudBuild: {}
    artifacts:
    - image: lms
      docker:
        cacheFrom:
          - lms
          - lms:latest
      requires:
      - image: common
        alias: BASE_IMG
- name: dev
  activation:
  - kubeContext: gke_core-learning-services-dev_us-central1_core-learning-services-dev-us-central1
  build:
    googleCloudBuild: {}
    artifacts:
    - image: gcr.io/core-learning-services-dev/lms
      docker:
        cacheFrom:
          - gcr.io/core-learning-services-dev/lms
          - gcr.io/core-learning-services-dev/lms:latest
      requires:
        - image: gcr.io/core-learning-services-dev/common
          alias: BASE_IMG
      sync:
        infer:
          - '**/*.py'
          - '**/*.json'
  deploy:
    kustomize:
      paths:
      - ./kustomize/dev