apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-response-theory
spec:
  template:
    spec:
      containers:
      - name: item-response-theory
        image: item-response-theory
        imagePullPolicy: IfNotPresent