apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: authentication
        image: gcr.io/aitutor-dev/authentication
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
        - name: DATABASE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: DATABASE_PREFIX
        - name: INSPACE_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: INSPACE_BASE_URL