apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms
spec:
  template:
    spec:
      serviceAccountName: ksa
      containers:
      - name: lms
        image: lms
        imagePullPolicy: Always
