CREATE TABLE IF NOT EXISTS statements (
        uuid STRING NOT NULL OPTIONS(description = "UUID"),
        actor STRUCT < uuid STRING NOT NULL OPTIONS(description = "UUID"),
        object_type STRING NOT NULL,
        name STRING NOT NULL,
        mbox STRING,
        mbox_sha1sum STRING,
        open_id STRING,
        account_homepage STRING,
        account_name STRING,
        members ARRAY < STRING >,
        user_id STRING > NOT NULL OPTIONS(description = "Actor/Agent"),
        verb STRUCT < uuid STRING NOT NULL,
        name STRING NOT NULL,
        url STRING NOT NULL,
        canonical_data STRING > NOT NULL OPTIONS(description = "Verb"),
        object STRUCT < uuid STRING NOT NULL,
        name STRING NOT NULL,
        authority STRING NOT NULL,
        canonical_data STRING > NOT NULL OPTIONS(description = "Object/Activity"),
        object_type STRING NOT NULL,
        result STRING,
        context STRING,
        timestamp TIMESTAMP,
        result_success BOOLEAN,
        result_completion BOOLEAN,
        result_score_raw FLOAT64,
        result_score_min FLOAT64,
        result_score_max FLOAT64,
        stored TIMESTAMP NOT NULL,
        authority STRING,
        attachments ARRAY < STRING >,
        session_id STRING NOT NULL
);