apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  template:
    spec:
      serviceAccountName: ksa
      containers:
      - name: authentication
        image: authentication
        imagePullPolicy: Always
        env:
        - name: DATABASE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: DATABASE_PREFIX
        - name: IS_DEVELOPMENT
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: IS_DEVELOPMENT
        - name: INSPACE_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: INSPACE_BASE_URL
        - name: EXTERNAL_USER_PROPERTY_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: EXTERNAL_USER_PROPERTY_PREFIX
