apiVersion: v1
kind: Service
metadata:
  name: user-management
  labels:
    app: user-management
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: user-management