apiVersion: v1
kind: Service
metadata:
  name: learning-record-service
  labels:
    app: learning-record-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: learning-record-service
