apiVersion: apps/v1
kind: Deployment
metadata:
  name: utils
spec:
  template:
    spec:
      containers:
      - name: utils
        image: utils
        imagePullPolicy: IfNotPresent
        env:
        - name: GCP_LEARNING_RESOURCE_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: GCP_LEARNING_RESOURCE_BUCKET
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: PROJECT_ID

