apiVersion: v1
kind: Service
metadata:
  name: deep-knowledge-tracing
  labels:
    app: deep-knowledge-tracing
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deep-knowledge-tracing