apiVersion: v1
kind: Service
metadata:
  name: student-learner-profile
  labels:
    app: student-learner-profile
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: student-learner-profile
