apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-record-service
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: ksa
      containers:
      - name: learning-record-service
        image: gcr.io/gcp-classroom-dev/learning-record-service
        imagePullPolicy: Always
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: PROJECT_ID
        - name: DATABASE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: DATABASE_PREFIX
