apiVersion: v1
kind: Service
metadata:
  name: learning-object-service
  labels:
    app: learning-object-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: learning-object-service
