name: Run Cypress tests after merge
on:
  pull_request:
    branches: [ "main" ]

jobs:
  e2eTests:
    name: Cypress Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install & run e2e tests
        uses: cypress-io/github-action@v5
        with:
          start: npx run cypress
          working-directory: experimental/e2e-frontend/cypress

      - name: Check status
        uses: actions/github-status@v1
        with:
          status: ${{ job.status }}
          context: Cypress E2E Tests