apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: credential-pathway-service
requires:
  - path: ../../common
    configs: [common]
    activeProfiles:
    - name: custom
      activatedBy: [custom]
    - name: dev
      activatedBy: [dev]
build:
  tagPolicy:
    gitCommit: {}
  local:
    concurrency: 0
  artifacts:
  - image: credential-pathway-service
    requires:
      - image: common
        alias: BASE_IMG
    sync:
      infer:
        - '**/*.py'
        - '**/*.json'
portForward:
- resourceType: service
  resourceName: credential-pathway-service
  port: 80
  localPort: 8888
deploy:
  kustomize:
    paths:
    - ./kustomize/minikube
profiles:
- name: custom
  build:
    googleCloudBuild: {}
    artifacts:
    - image: credential-pathway-service
      docker:
        cacheFrom:
          - credential-pathway-service:latest
      requires:
        - image: common
          alias: BASE_IMG
  deploy:
    kustomize:
      paths:
      - ./kustomize/custom
- name: dev
  build:
    googleCloudBuild: {}
    artifacts:
    - image: gcr.io/aitutor-dev/credential-pathway-service
      docker:
        cacheFrom:
          - gcr.io/aitutor-dev/credential-pathway-service:latest
      requires:
        - image: gcr.io/aitutor-dev/common
          alias: BASE_IMG
      sync:
        infer:
          - '**/*.py'
          - '**/*.json'
  deploy:
    kustomize:
      paths:
      - ./kustomize/dev
